question_data = [
    {"response_code": 0, "results": [{"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The first computer bug was formed by faulty wires.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "&quot;Windows NT&quot; is a monolithic kernel.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "MacOS is based on Linux.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "The first dual-core CPU was the Intel Pentium D.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Android versions are named in alphabetical order.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                                      "correct_answer": "False", "incorrect_answers": ["True"]}]}
]
